// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lztlglumldvasfnoyins.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dGxnbHVtbGR2YXNmbm95aW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNjkyMTYsImV4cCI6MjA4Mzg0NTIxNn0.Fde9h5ffnur_ZrTXa6pkvptiX7PwQfiHAg-7BRsUqk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});